### ISSUE TITLE
aero::print::print_hex not necessary

### ISSUE THREAD

**Issue by jeffstjean** [UWO-Aero-Design/aero-cpp-lib#2]
Both printf and Arduino's Serial.println() provide implementation for printing hex. 

`printf("%#010x\n", 78);`
`Serial.print(78, HEX);`

**Comment by cbaron3** [comment]
print_hex prints a buffer of characters into char format, not just a single char.

The code isnt complicated but it prevents the next user from having to write their own buffer printing function and debug it. 

it also allows for printing on arduino, using the arduino streaming library, or just simply with cout if you are on desktop

its just a standard buffer printer that is very useful for debugging communications
